name: jdk-support on ubuntu

on:
  push: 
    branches: [ main ]
  workflow_dispatch:

jobs:
    # stage 1: build and test the application
    build-setup-oracle:
        runs-on: ubuntu-latest
        steps:
        # step 1: checkout the code from the repository
        - name: setup-java
          uses: actions/setup-java@v5
          with:
            distribution: 'oracle'
            java-version: '17'

        - name: run on java code
          run: | 
            java --version
            echo "####################"
            javac --version

    build-setup-temurin:
        needs: build-setup-oracle
        runs-on: ubuntu-latest
        steps:
          - name: setup-java
            uses: actions/setup-java@v5
            with:
              distribution: 'temurin'
              java-version: '17'

          - name: run on java code
            run: |
              java --version
              echo "##########################"
              javac --version
              gradle --version


    build-for-gradle:
      needs: build-setup-oracle
      runs-on: ubuntu-latest
      steps:
        - name: setup-java
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin'
            java-version: '17'
        
        - name: Setup Android SDK
          uses: android-actions/setup-android@v3

        - name: check android home
          run: |
            echo "################"
            echo "home:"
            echo $HOME
            echo "################"
            echo "android home:"
            echo $ANDROID_HOME
            echo "################"
            echo "path:"
            echo $PATH

        - name: setup or check java with gradle
          run: | 
            java --version
            which java
            echo "############################"
            which gradle
            gradle --version
            sudo gem install fastlane

        - name: check all things 
          run: | 
           gradle -v
           java -version
           javac -version
           free -h
           df -h
            
