name: jdk-support on ubuntu

on:
  push: 
    branches: [ main ]
  workflow_dispatch:

jobs:
    # stage 1: build and test the application
    build-setup:
        runs-on: ubuntu-latest
        steps:
        # step 1: checkout the code from the repository
        - name: Checkout code
          uses: actions/setup-java@v5
          with:
            distribution: 'oracle'
            java-version: '17'

        - name: run on java code
          run: | 
            java --version
            javac --version
            java -cp java HelloWorldApp
