name: jdk-support on ubuntu

on:
  push: 
    branches: [ main ]
  workflow_dispatch:

jobs:
    # stage 1: build and test the application
    build-setup-oracle:
        runs-on: ubuntu-latest
        steps:
        # step 1: checkout the code from the repository
        - name: setup-java
          uses: actions/setup-java@v5
          with:
            distribution: 'oracle'
            java-version: '17'

        - name: run on java code
          run: | 
            java --version
            echo "####################"
            javac --version

    build-setup-temurin:
        runs-on: ubuntu-latest
        steps:
          - name: setup-java
            uses: actions/setup-java@5
            with:
              distribution: 'temurin'
              java-version: '17'

          - name: run on java code
            run: |
              java --version
              echo "##########################"
              javac --varsion
