name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: | 
          npm test
          ls -la 
          ls -la coverage
          tree coverage

      - name: Show summary report
        run: |
          echo "The coverage summary is: $SUMMARY_REPORT"

      - name: Upload coverage folder
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
