name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npx jest --coverage --json --outputFile=coverage/report.json

      - name: Extract coverage summary
        id: coverage_summary
        run: |
          SUMMARY=$(jq -r '.coverageMap["server.js"].lines.pct' coverage/report.json)
          echo "SUMMARY_REPORT=Coverage lines: $SUMMARY%" >> $GITHUB_ENV
          echo "Coverage summary: $SUMMARY%"

      - name: Show summary report
        run: |
            echo "The coverage summary is: $SUMMARY_REPORT"

      - name: Upload coverage folder
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage


