name: Node.js CI with Jest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run Jest tests with coverage
      - name: Run Jest tests
        run: npm test

      # 5. Publish Jest JUnit report for dashboard
      - name: Publish Jest test results
        uses: dorny/test-reporter@v1
        with:
          name: Jest Tests
          path: reports/junit/jest-junit.xml
          reporter: junit
          token: ${{ github.token }}

      # 6. Upload coverage report as artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage
