name: Node.js CI with Jest

on:
  push:
    paths-ignore:
      - README.md
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v5

      - name: check cache
        run: |
          ls -la /opt/hostedtoolcache/node/22.20.0/x64
          
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          
      - name: install dependency
        run: npm install
      
      - name: check tf
        uses: hashicorp/setup-terraform@v3

      - name: check tf version
        run: terraform version

      # - name: check script
      #   uses: actions/github-script@v8
      #   with:
      #     script: |
      #       console.log("hello");
      #       console.log("");
      #       console.log(context);

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - uses: Kesin11/actions-timeline@v2
        with:
          show-waiting-runner: true
