name: Node.js CI with Jest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v5

      # - name: Screenshot Website
      #   uses: swinton/screenshot-website@v1.x
      #   with:
      #     source: https://nodko.onrender.com
      #     destination: screenshot.png

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - uses: Kesin11/actions-timeline@v2
        with:
          show-waiting-runner: true
