name: Node.js CI with Jest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v5

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run Jest tests with coverage
      - name: Run Jest tests
        run: |
          npm test >> covrage.txt
          ls -la
          mv covrage.txt coverage/
          echo ${{ github.workspace }}
          cd coverage
          ls -la
          echo "#############################"
          pwd
          echo "#############################"
          
      - name: check test 
        run: |
          echo "${{ secrets.DEV_ENV }}" > .env.production
          cat .env.production
      # 5. Publish Jest JUnit report for dashboard
      - name: Publish Jest test results
        uses: dorny/test-reporter@v2
        with:
          name: Jest Tests
          path: 'reports/junit/*.xml'
          reporter: jest-junit
#          token: ${{ github.token }}

      # 6. Upload coverage report as artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
      
      - name: remove coverage report
        run: | 
          rm -rf coverage
          rm -rf reports
          rm coverage.txt
          ls -la
